In [52]:
import torch
import torch.nn as nn

d_1, d_2 = 5, 3
r_1 = torch.ones(d_1, 32, 32)
r_2 = torch.ones(d_2, 32, 32)
for i in range(d_1):
    r_1[i] = i
for i in range(d_2):
    r_2[i] = i

# step1
product = r_1.unsqueeze(1) * r_2.unsqueeze(0)
print(product.shape)
for i in range(d_1):
    for j in range(d_2):
        print(product[i, j, 0, 0].item(), end=' ')
    print()
print()

# initialize a
a = torch.ones(d_1, d_2, 1, 1)
a[-1, -1] = 0
print(a.shape)
for i in range(d_1):
    for j in range(d_2):
        print(a[i, j, 0, 0].item(), end=' ')
    print()
print()

# step2
temp_product = (product * a).sum(dim=(0, 1), keepdim=False)
print(temp_product.shape)
print(temp_product)

torch.Size([5, 3, 32, 32])
0.0 0.0 0.0 
0.0 1.0 2.0 
0.0 2.0 4.0 
0.0 3.0 6.0 
0.0 4.0 8.0 

torch.Size([5, 3, 1, 1])
1.0 1.0 1.0 
1.0 1.0 1.0 
1.0 1.0 1.0 
1.0 1.0 1.0 
1.0 1.0 0.0 

torch.Size([32, 32])
tensor([[22., 22., 22.,  ..., 22., 22., 22.],
        [22., 22., 22.,  ..., 22., 22., 22.],
        [22., 22., 22.,  ..., 22., 22., 22.],
        ...,
        [22., 22., 22.,  ..., 22., 22., 22.],
        [22., 22., 22.,  ..., 22., 22., 22.],
        [22., 22., 22.,  ..., 22., 22., 22.]])


In [ ]:
import torch
import torch.nn as nn

d_1, d_2 = 5, 3
r_1 = torch.ones(d_1, 32, 32)
r_2 = torch.ones(d_2, 32, 32)
for i in range(d_1):
    r_1[i] = i
for i in range(d_2):
    r_2[i] = i

# step1
product = r_1.unsqueeze(1) * r_2.unsqueeze(0)
print(product.shape)
for i in range(d_1):
    for j in range(d_2):
        print(product[i, j, 0, 0].item(), end=' ')
    print()
print()


# step2
class test_model(nn.Module):
    def __init__(self, d_1, d_2):
        super(test_model, self).__init__()
        self.fc1 = nn.Linear(d_1, 1)
        self.fc2 = nn.Linear(d_2, 1)

    def forward(self, x):
        x = x.permute(1, 2, 3, 0)
        x = self.fc1(x).squeeze(-1)
        x = x.permute(1, 2, 0)
        x = self.fc2(x).squeeze(-1)
        return x
    

model = test_model(d_1, d_2)
result = model(product)
print(result.shape)
print(model.fc1.weight.shape)
print(model.fc2.weight.shape)

torch.Size([5, 3, 32, 32])
0.0 0.0 0.0 
0.0 1.0 2.0 
0.0 2.0 4.0 
0.0 3.0 6.0 
0.0 4.0 8.0 

torch.Size([5, 3, 32, 32])
torch.Size([3, 32, 32, 5])
torch.Size([3, 32, 32])
torch.Size([32, 32, 3])
torch.Size([32, 32])
torch.Size([32, 32])
torch.Size([1, 5])
torch.Size([1, 3])


In [16]:
import torch
import torch.nn as nn

m = nn.Conv1d(4, 2, 3, stride=1)
input = torch.randn(1, 4, 4)
print(input)
print(input.size())
output = m(input)
print(output.size())

tensor([[[ 0.0982,  2.7188,  1.0380,  0.9596],
         [-2.3485,  2.4026, -0.6437, -0.6879],
         [ 1.6365, -2.3075, -0.0965, -1.4783],
         [ 2.3570, -1.6293,  0.8727,  1.4234]]])
torch.Size([1, 4, 4])
torch.Size([1, 2, 2])


In [35]:
import torch
m = 4
a_v = torch.randn(1, 4, 4)
print(a_v.shape)
print(a_v.unsqueeze(1).shape)
av_powers = [torch.pow(a_v, i) for i in range(m)]
print(av_powers.shape)

for i in range(m):
    print(av_powers[i])

torch.Size([1, 4, 4])
torch.Size([1, 1, 4, 4])


AttributeError: 'list' object has no attribute 'shape'

In [25]:
bs_channel, sinp, feature_dim = 40, 32, 32
single_identity = torch.eye(feature_dim).unsqueeze(0).expand(bs_channel, -1, -1)
print(single_identity.size())
print(single_identity)

torch.Size([40, 32, 32])
tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]],

        ...,

        [[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.